name: Generate Changelog
permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  # Allows you to manually trigger the workflow from the GitHub Actions UI

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Ruby 3.2.2
        uses: ruby/setup-ruby@872f6a78a21b718383d52e8aee0539379227f233
        with:
          ruby-version: '3.2'

      - name: Install GitHub Changelog Generator
        run: |
          gem install github_changelog_generator

      - name: Generate Changelog
        run: |
          github_changelog_generator --user Rovetown --project HarryPotterRenewed

      - name: Commit and Push Changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Updated CHANGELOG.md"
          git fetch origin
          git rebase --strategy-option=theirs origin/main
          git push
