name: Issue assignment

on:
  issues:
    types: [opened, edited, milestoned]
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v2.1.2
        with:
          assignees: Rovetown,rovetown
          allowSelfAssign: false