name: TOTO to Issue

on:
  workflow_dispatch:

jobs:
  todo-to-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.1.10